spring.application.name=event-gateway
server.port=8080
account-service.base-url=http://localhost:8081

spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.root=INFO
logging.level.com.schwab=DEBUG

resilience4j.circuitbreaker.instances.accountServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountServiceCB.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.accountServiceCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.retry.instances.accountServiceRetry.maxAttempts=3
resilience4j.retry.instances.accountServiceRetry.waitDuration=1000
