spring.application.name=event-gateway

server.port=8080

account-service.base-url=${ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

spring.datasource.url=jdbc:h2:mem:eventdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.root=INFO
logging.level.com.eventledger.gateway=DEBUG

resilience4j.circuitbreaker.instances.accountServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountServiceCB.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.accountServiceRetry.maxAttempts=3
resilience4j.retry.instances.accountServiceRetry.waitDuration=1s