spring.application.name=account-service
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

server.port=8081

spring.datasource.url=jdbc:h2:mem:accountdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.root=INFO
logging.level.com.schwab=DEBUG
